test_class(c_tester);
test_class(c_dummy_child);
test_class(c_tuple);
test_class(c_result);
test_class(c_signature);
test_class(c_interface);
test_class(c_mock);
test_class(c_injection);
test_class(c_ioc_container);