// global settings map
#macro key_settings_creation_date			"settings_creation_date"
#macro key_settings_window_width			"window_width"
#macro key_settings_window_height			"window_height"
#macro key_settings_window_fullscreen		"window_fullscreen"
#macro key_settings_window_aa_level			"window_aa_level"
#macro key_settings_window_vsync			"window_vsync"
#macro key_settings_window_x				"window_x"
#macro key_settings_window_y				"window_y"
#macro key_settings_sound_volume_master		"sound_volume_master"
#macro key_settings_sound_volume_voice		"sound_volume_voice"
#macro key_settings_sound_volume_sfx		"sound_volume_sfx"
#macro key_settings_sound_volume_music		"sound_volume_music"