
test_ghost_destruct_one_basetile();
test_ghost_destruct_one_basetile_wall();
test_ghost_destruct_four_basetiles();
test_ghost_nine_basetiles_destruct_center();
test_ghost_nine_basetiles_destruct_corner();
test_ghost_nine_basetiles_destruct_side();